# Generated by Django 3.1.2 on 2021-11-30 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='quesType',
            field=models.CharField(blank=True, choices=[('l', 'Check your listening skills'), ('p', 'Check your pronunciation skills')], default='l', help_text='Тип вопроса', max_length=1),
        ),
        migrations.AlterField(
            model_name='test',
            name='desc',
            field=models.TextField(help_text='Описание теста', max_length=200),
        ),
    ]
