# Generated by Django 3.1.2 on 2022-03-30 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20211202_1123'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audiofile', models.FileField(blank=True, help_text='Аудио-файлы при необходимости', null=True, upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='quesType',
            field=models.CharField(blank=True, choices=[('l', 'Check your listening skills'), ('p', 'Check your pronunciation skills'), ('v', 'Determine if the consonants are voiced or voiceless')], default='l', help_text='Тип вопроса', max_length=1),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='audio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.audioanswer'),
        ),
    ]
