# Generated by Django 3.1.2 on 2022-04-06 05:18

from django.db import migrations, models
import quiz.models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20220330_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audioanswer',
            name='audiofile',
            field=models.FileField(blank=True, help_text='Аудио-файлы при необходимости', null=True),
        ),
    ]
