# Generated by Django 3.1.2 on 2022-06-14 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20220406_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentanswer',
            name='audio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.audioanswer'),
        ),
    ]
